const data = [
  {
    DEPARTMENT: "Communication",
    SUBSECTION: "Communication",
    DOC_COUNT: 60,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "Communication",
    SUBSECTION: "Communication",
    DOC_COUNT: 42,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "Communication",
    SUBSECTION: "Communication",
    DOC_COUNT: 47,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "Communication",
    SUBSECTION: "Communication",
    DOC_COUNT: 39,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "Communication",
    SUBSECTION: "Communication",
    DOC_COUNT: 47,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "Corporate Affairs",
    SUBSECTION: "CA",
    DOC_COUNT: 57,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "Corporate Affairs",
    SUBSECTION: "CA",
    DOC_COUNT: 6,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "Corporate Affairs",
    SUBSECTION: "CA",
    DOC_COUNT: 135,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "Drilling Fluid Services",
    SUBSECTION: "Drilling Fluid Services",
    DOC_COUNT: 35,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "Drilling Fluid Services",
    SUBSECTION: "Drilling Fluid Services",
    DOC_COUNT: 53,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "Drilling Fluid Services",
    SUBSECTION: "Drilling Fluid Services",
    DOC_COUNT: 3,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "Drilling Fluid Services",
    SUBSECTION: "Drilling Fluid Services",
    DOC_COUNT: 14,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "Drilling Fluid Services",
    SUBSECTION: "Drilling Fluid Services",
    DOC_COUNT: 20,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "ECMP",
    DOC_COUNT: 2,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "ECMP",
    DOC_COUNT: 2,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "ED",
    DOC_COUNT: 1,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "ED",
    DOC_COUNT: 1,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "GS",
    DOC_COUNT: 5,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "GS",
    DOC_COUNT: 428,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "GS",
    DOC_COUNT: 1,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "GS",
    DOC_COUNT: 5,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "GS-MudLoging",
    DOC_COUNT: 5,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "PG",
    DOC_COUNT: 101,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "PG",
    DOC_COUNT: 122,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "PG-South",
    DOC_COUNT: 9,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "PG-South",
    DOC_COUNT: 4,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "PG-South East",
    DOC_COUNT: 3,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "Exploration",
    SUBSECTION: "PG-South East",
    DOC_COUNT: 2,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "Exploration (TDL)",
    SUBSECTION: "TDL",
    DOC_COUNT: 13,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "Finance & Accounts",
    SUBSECTION: "Finance & Accounts",
    DOC_COUNT: 84,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "Finance & Accounts",
    SUBSECTION: "Finance & Accounts",
    DOC_COUNT: 11,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "Finance & Accounts",
    SUBSECTION: "Finance & Accounts",
    DOC_COUNT: 7,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "Finance & Accounts",
    SUBSECTION: "Finance & Accounts",
    DOC_COUNT: 2,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR - Policy",
    DOC_COUNT: 13,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR - Policy",
    DOC_COUNT: 26,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR - Policy",
    DOC_COUNT: 17,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR - Policy",
    DOC_COUNT: 27,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR - Policy",
    DOC_COUNT: 12,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-B",
    DOC_COUNT: 2,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-D",
    DOC_COUNT: 3,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-E",
    DOC_COUNT: 124,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-E",
    DOC_COUNT: 168,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-E",
    DOC_COUNT: 135,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-E",
    DOC_COUNT: 99,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-E",
    DOC_COUNT: 132,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-G",
    DOC_COUNT: 20,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-G",
    DOC_COUNT: 27,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-G",
    DOC_COUNT: 18,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "HR(Ops)-G",
    DOC_COUNT: 27,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "Pension",
    DOC_COUNT: 79,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "Pension",
    DOC_COUNT: 31,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "Pension",
    DOC_COUNT: 324,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "Pension",
    DOC_COUNT: 184,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "HR",
    SUBSECTION: "Pension",
    DOC_COUNT: 85,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "HSEQ",
    SUBSECTION: "HSEQ",
    DOC_COUNT: 4,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "HSEQ",
    SUBSECTION: "HSEQ",
    DOC_COUNT: 109,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "HSEQ",
    SUBSECTION: "HSEQ",
    DOC_COUNT: 50,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "JV&BD",
    SUBSECTION: "JV&BD",
    DOC_COUNT: 1,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "JV&BD",
    SUBSECTION: "JV&BD",
    DOC_COUNT: 9,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "JV&BD",
    SUBSECTION: "JV&BD",
    DOC_COUNT: 61,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "MD Secretariat",
    SUBSECTION: "MD Secretariat",
    DOC_COUNT: 278,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "MD Secretariat",
    SUBSECTION: "MD Secretariat",
    DOC_COUNT: 196,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "MD Secretariat",
    SUBSECTION: "MD Secretariat",
    DOC_COUNT: 288,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "MD Secretariat",
    SUBSECTION: "MD Secretariat",
    DOC_COUNT: 368,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "MD Secretariat",
    SUBSECTION: "MD Secretariat",
    DOC_COUNT: 214,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "MMD",
    SUBSECTION: "MMD",
    DOC_COUNT: 13,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "RMD",
    SUBSECTION: "RMD",
    DOC_COUNT: 246,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Foreign - A",
    DOC_COUNT: 22,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Foreign - A",
    DOC_COUNT: 18,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Foreign - B",
    DOC_COUNT: 10,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Foreign - B",
    DOC_COUNT: 3,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Foreign - C",
    DOC_COUNT: 33,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Foreign - C",
    DOC_COUNT: 43,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Foreign - C",
    DOC_COUNT: 35,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Foreign - C",
    DOC_COUNT: 23,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Foreign - E",
    DOC_COUNT: 30,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Local",
    DOC_COUNT: 14,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Local",
    DOC_COUNT: 35,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Local",
    DOC_COUNT: 7,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Local",
    DOC_COUNT: 24,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Local",
    DOC_COUNT: 31,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Services",
    DOC_COUNT: 9,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Services",
    DOC_COUNT: 1,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Services",
    DOC_COUNT: 6,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Services",
    DOC_COUNT: 5,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Services",
    DOC_COUNT: 7,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Services - A",
    DOC_COUNT: 16,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "SCM",
    SUBSECTION: "SCM - Services - A",
    DOC_COUNT: 30,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "Systems",
    SUBSECTION: "ERP",
    DOC_COUNT: 4,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "Systems",
    SUBSECTION: "IT Apps",
    DOC_COUNT: 5,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "Systems",
    SUBSECTION: "IT Apps",
    DOC_COUNT: 78,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "Systems",
    SUBSECTION: "IT Apps",
    DOC_COUNT: 84,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "Systems",
    SUBSECTION: "IT Apps",
    DOC_COUNT: 49,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
  {
    DEPARTMENT: "Systems",
    SUBSECTION: "IT Operations",
    DOC_COUNT: 76,
    YEAR: 2022,
    MONTHNAME: "August",
    MONTH: 8,
  },
  {
    DEPARTMENT: "Systems",
    SUBSECTION: "IT Operations",
    DOC_COUNT: 57,
    YEAR: 2022,
    MONTHNAME: "July",
    MONTH: 7,
  },
  {
    DEPARTMENT: "Systems",
    SUBSECTION: "IT Operations",
    DOC_COUNT: 82,
    YEAR: 2022,
    MONTHNAME: "November",
    MONTH: 11,
  },
  {
    DEPARTMENT: "Systems",
    SUBSECTION: "IT Operations",
    DOC_COUNT: 51,
    YEAR: 2022,
    MONTHNAME: "October",
    MONTH: 10,
  },
  {
    DEPARTMENT: "Systems",
    SUBSECTION: "IT Operations",
    DOC_COUNT: 56,
    YEAR: 2022,
    MONTHNAME: "September",
    MONTH: 9,
  },
];

export default data;
